org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true

# Fix for namespace issue with older plugins
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=false
# This builtInKotlin flag was added automatically by Flutter migrator
# Comentado temporariamente para testar quais plugins foram migrados:
# android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
# android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
